#!/bin/bash
# dosmplotofl — offline plots

PORT=5555
LJ_FILE="50000/lj.dat"
VV_FILE="50000/vv.dat"
TAIL_SIZE=$((1 * 2 ** 10))
SLEEP=1

gnuplot -persist <<EOF &
set grid
set key left top
set xlabel 'r / σ'
set ylabel 'Uij(r)'

while (1) {
  plot "< tail -n ${TAIL_SIZE} ${LJ_FILE} | awk 'NF==2{print}' | sort -g -k1,1" using 1:2 with lines title "LJ potentiel"
  pause ${SLEEP}
}
EOF

gnuplot -persist <<EOF &
set grid
set key left top
set xlabel 't'
set ylabel 'Energy'

while (1) {
  plot \
    "< tail -n ${TAIL_SIZE} ${VV_FILE} | awk 'NF==5{print}'" using 1:2 with lines title "Ek", \
    "< tail -n ${TAIL_SIZE} ${VV_FILE} | awk 'NF==5{print}'" using 1:3 with lines title "Ep", \
    "< tail -n ${TAIL_SIZE} ${VV_FILE} | awk 'NF==5{print}'" using 1:4 with lines title "Etot"
  pause ${SLEEP}
}
EOF

gnuplot -persist <<EOF &
set grid
set key left top
set xlabel 't'
set ylabel 'Temperature'

while (1) {
  plot "< tail -n ${TAIL_SIZE} ${VV_FILE} | awk 'NF==5{print}'" using 1:5 with lines title "T"
  pause ${SLEEP}
}
EOF

echo "Gnuplot running..."

unset TAIL_SIZE SLEEP PORT LJ_FILE VV_FILE

wait
