#include "dosmFactor.hpp"
#include "dosmLawLennardJonesPeriodic.hpp"
#include <cstdio>
#include <fstream>
#include <stdexcept>

namespace dosm
{

	DosmFactor::DosmFactor(const str_t& file)
	{
		loadFile(file);
	}

	void DosmFactor::loadFile(const str_t& file)
	{
		std::ifstream in(file);
		if (!in)
		{
			DOSM_LOG_ERROR("Cannot open file: " + file);
			throw std::runtime_error("dosmFactor: cannot open file");
		}

		in.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

		vector_t<DosmParticle> particles;
		const r64_t mass   = 1.0;
		const r64_t charge = 0.0;

		i32_t type;
		r64_t x, y, z;
		while (in >> type >> x >> y >> z)
		{
			DosmParticle particle(mass, charge);
			particle.position(0) = x;
			particle.position(1) = y;
			particle.position(2) = z;
			particles.push_back(particle);
		}

		DosmParticleSnap::Snap snap0;
		snap0.t = 0.0;
		snap0.particles = particles;

		dosmParticleSnap.snaps.clear();
		dosmParticleSnap.snaps.push_back(snap0);

		DOSM_LOG_INFO("Loaded " + std::to_string(particles.size()) + " particles");
	}

	void DosmFactor::outFile(void)
	{
		const str_t csvFile = "dosmdata.csv";
		const str_t pdbFile = "dosmvisual.pdb";
		const r64_t boxLength = 25.0;

		std::ofstream csv(csvFile);
		if (!csv)
		{
			DOSM_LOG_ERROR("Cannot open CSV file: " + csvFile);
			return;
		}

		std::ofstream pdb(pdbFile);
		if (!pdb)
		{
			DOSM_LOG_ERROR("Cannot open PDB file: " + pdbFile);
			return;
		}

		chr_t line[256];

		snprintf(
				line,
				sizeof(line),
				"snap\tt\tid\tmass\tcharge\tx\ty\tz\tvx\tvy\tvz\tfx\tfy\tfz\tforce\tenergy\n"
				);
		csv << line;

		snprintf(line, sizeof(line), "HEADER    DOSM PARTICLES\n");
		pdb << line;

		snprintf(line, sizeof(line), "REMARK    Generated by dosmetric\n");
		pdb << line;

		snprintf(
				line,
				sizeof(line),
				"CRYST1%9.3f%9.3f%9.3f  90.00  90.00  90.00 P 1\n",
				boxLength, boxLength, boxLength
				);
		pdb << line;

		const idx_t nSnap = dosmParticleSnap.snaps.size();

		for (idx_t i = 0; i < nSnap; ++i)
		{
			const auto& snap = dosmParticleSnap.snaps[i];

			snprintf(
					line,
					sizeof(line),
					"MODEL     %d\n",
					i + 1
					);
			pdb << line;

			const idx_t n = snap.particles.size();
			for (idx_t j = 0; j < n; ++j)
			{
				const DosmParticle& particle = snap.particles[j];
				const r64_t force = particle.force.norm();

				snprintf(
						line,
						sizeof(line),
						"%d\t%.6f\t%d\t%.3f\t%.3f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\n",
						i,
						snap.t,
						j,
						particle.mass,
						particle.charge,
						particle.position(0),
						particle.position(1),
						particle.position(2),
						particle.velocity(0),
						particle.velocity(1),
						particle.velocity(2),
						particle.force(0),
						particle.force(1),
						particle.force(2),
						force,
						particle.energy
						);
				csv << line;

				snprintf(
						line,
						sizeof(line),
						"ATOM  %5d  X   SIM %4d    %8.3f%8.3f%8.3f%6.2f%6.2f\n",
						j + 1,
						1,
						particle.position(0),
						particle.position(1),
						particle.position(2),
						force,              
						particle.energy    
						);

				pdb << line;
			}

			snprintf(line, sizeof(line), "ENDMDL\n");
			pdb << line;

			DOSM_PROGRESS("Generating output", i + 1, nSnap);
		}

		DOSM_LOG_INFO("Generated outputs: " + csvFile + ", " + pdbFile);
	}


	void DosmFactor::run(void)
	{
		DOSM_LOG_DEBUG("Factor::run() entered");

		vector_t<DosmParticle>& particles = dosmParticleSnap.snaps.back().particles;
		// idosmLaw = std::make_unique<DosmLawLennardJones>(particles, 1.0, 1.0);
		idosmLaw = std::make_unique<DosmLawLennardJonesPeriodic>(particles, 1.0, 1.0, 50.0, 10.0);	
		IDosmLaw::Result result;

		dosmParallel.init();
		dosmParallel.dispatch(1, [&](idx_t) { idosmLaw->kernel(&result); });
		dosmParallel.release();

		if (result.particles == nullptr)
		{
			DOSM_LOG_ERROR("Kernel failed");
			return;
		}

		particles = *result.particles;
		DOSM_LOG_INFO("Lennard-Jones total energy = " + std::to_string(result.energy));

		outFile();

		DOSM_LOG_INFO("Factor::run() done");
	}

} // namespace dosm
